# [START gae_python37_custom_runtime]
runtime: python37
entrypoint: uwsgi --http-socket :8080 --wsgi-file main.py --callable app --master --processes 1 --threads 2
# [END gae_python37_custom_runtime]

#runtime: python
#env: flex
#entrypoint: gunicorn -b :$PORT main:app
#
#runtime_config:
#  python_version: 3
#
## This sample incurs costs to run on the App Engine flexible environment.
## The settings below are to reduce costs during testing and are not appropriate
## for production use. For more information, see:
## https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
#manual_scaling:
#  instances: 1
#resources:
#  cpu: 1
#  memory_gb: 0.5
#  disk_size_gb: 5